# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.9'

services:
  webservice:
    image: webservice:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - webservice_storage:/app/data
      - ~/.vsdbg:/remote_debugger:rw

  web_app:
    image: web_app:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
    env_file:
      - rms-variables.env
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    
volumes:
  webservice_storage:
