# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.9'

services:
  web_service:
    image: web_service:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - rms-variables.env
    volumes:
      - webservice_storage:/app/data
      - webservice_recordings:/app/data/recordings
      - ~/.vsdbg:/remote_debugger:rw

  web_app:
    image: web_app:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
    env_file:
      - rms-variables.env
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  inference_service:
    image: inference_service:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./inference_service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - rms-variables.env
    volumes:
      - inference_service_storage:/app/data
      - ~/.vsdbg:/remote_debugger:rw

volumes:
  webservice_storage:
  webservice_recordings:
  inference_service_storage:
