# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.9'

services:
  webservice:
    image: webservice:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_service/Dockerfile
    volumes:
      - webservice_storage:/app/data

  web_app:
    image: web_app:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
volumes:
  webservice_storage:
