version: '3.9'

services:
  web_service:
    image: web_service:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_service/Dockerfile
    env_file:
      - rms-variables.env
      - s3-secrets.env
    volumes:
      - webservice_storage:/app/data
      - webservice_recordings:/app/data/recordings

  web_app:
    image: web_app:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
    env_file:
      - rms-variables.env
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  
  device_emulator:
    image: device_emulator:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./device_emulator/Dockerfile
    env_file:
      - rms-variables.env
    volumes:
      - webservice_recordings:/app/data/recordings

  inference_service:
    image: inference_service:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./inference_service/Dockerfile
    env_file:
      - rms-variables.env
    volumes:
      - inference_service_storage:/app/data
    profiles:
      - donotstart

  models_service:
    image: models_service:latest
    network_mode: "host"
    build:
      context: ./models_service
      dockerfile: ./Dockerfile
    env_file:
      - rms-variables.env
    volumes:
      - models_service_storage:/app/data
      - ~/.vsdbg:/remote_debugger:rw

volumes:
  webservice_storage:
  webservice_recordings:
  inference_service_storage:
  models_service_storage:
