version: '3.9'

services:
  webservice:
    image: webservice:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_service/Dockerfile
    env_file:
      - rms-variables.env
    volumes:
      - webservice_storage:/app/data
      - webservice_recordings:/app/data/recordings

  web_app:
    image: web_app:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
    env_file:
      - rms-variables.env
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    

volumes:
  webservice_storage:
  webservice_recordings:
