version: '3.9'

services:
  web_service:
    image: web_service:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_service/Dockerfile
    env_file:
      - rms-variables.env
    volumes:
      - webservice_storage:/app/data
      - webservice_recordings:/app/data/recordings
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  web_app:
    image: web_app:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
    env_file:
      - rms-variables.env
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  
  device_emulator:
    image: device_emulator:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./device_emulator/Dockerfile
    env_file:
      - rms-variables.env
    volumes:
      - webservice_recordings:/app/data/recordings
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  inference_service:
    image: inference_service:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: ./inference_service/Dockerfile
    env_file:
      - rms-variables.env
    volumes:
      - inference_service_storage:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    profiles:
      - donotstart

volumes:
  webservice_storage:
  webservice_recordings:
  inference_service_storage:
